package de.foopara.phpcsmd.option.phpcs;

public class DynamicPhpcsSniffRegistry extends GenericPhpcsSniffRegistry {

    public DynamicPhpcsSniffRegistry() {
        this.add(new PhpcsSniff("Generic.Classes.DuplicateClassName", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.EmptyStatement", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.ForLoopShouldBeWhileLoop", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.ForLoopWithTestFunctionCall", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.JumbledIncrementer", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.UnconditionalIfStatement", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.UnnecessaryFinalModifier", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.UnusedFunctionParameter", null, null));
        this.add(new PhpcsSniff("Generic.CodeAnalysis.UselessOverridingMethod", null, null));
        this.add(new PhpcsSniff("Generic.Commenting.Fixme", "Highlight FIXME comments", "comment"));
        this.add(new PhpcsSniff("Generic.Commenting.Todo", "Highlight TODO comments", "comment"));
        this.add(new PhpcsSniff("Generic.ControlStructures.InlineControlStructure", null, null));
        this.add(new PhpcsSniff("Generic.Debug.ClosureLinter", null, null));
        this.add(new PhpcsSniff("Generic.Debug.JSHint", null, null));
        this.add(new PhpcsSniff("Generic.Files.ByteOrderMark", null, null));
        this.add(new PhpcsSniff("Generic.Files.EndFileNewline", null, null));
        this.add(new PhpcsSniff("Generic.Files.LineEndings", null, null));
        this.add(new PhpcsSniff("Generic.Files.LineLength", null, null));
        this.add(new PhpcsSniff("Generic.Formatting.DisallowMultipleStatements", null, null));
        this.add(new PhpcsSniff("Generic.Formatting.MultipleStatementAlignment", null, null));
        this.add(new PhpcsSniff("Generic.Formatting.NoSpaceAfterCast", null, null));
        this.add(new PhpcsSniff("Generic.Formatting.SpaceAfterCast", null, null));
        this.add(new PhpcsSniff("Generic.Functions.CallTimePassByReference", null, null));
        this.add(new PhpcsSniff("Generic.Functions.FunctionCallArgumentSpacing", null, null));
        this.add(new PhpcsSniff("Generic.Functions.OpeningFunctionBraceBsdAllman", null, null));
        this.add(new PhpcsSniff("Generic.Functions.OpeningFunctionBraceKernighanRitchie", null, null));
        this.add(new PhpcsSniff("Generic.Metrics.CyclomaticComplexity", "calculate cyclomatic complexity", "complex"));
        this.add(new PhpcsSniff("Generic.Metrics.NestingLevel", "calculate nesting level", "complex"));
        this.add(new PhpcsSniff("Generic.NamingConventions.CamelCapsFunctionName", null, null));
        this.add(new PhpcsSniff("Generic.NamingConventions.ConstructorName", null, null));
        this.add(new PhpcsSniff("Generic.NamingConventions.UpperCaseConstantName", null, null));
        this.add(new PhpcsSniff("Generic.PHP.DeprecatedFunctions", "show deprecated functions", "forbidden"));
        this.add(new PhpcsSniff("Generic.PHP.DisallowShortOpenTag", null, null));
        this.add(new PhpcsSniff("Generic.PHP.ForbiddenFunctions", "show forbidden functions", "forbidden"));
        this.add(new PhpcsSniff("Generic.PHP.LowerCaseConstant", null, null));
        this.add(new PhpcsSniff("Generic.PHP.NoSilencedErrors", null, null));
        this.add(new PhpcsSniff("Generic.PHP.UpperCaseConstant", null, null));
        this.add(new PhpcsSniff("Generic.Strings.UnnecessaryStringConcat", null, null));
        this.add(new PhpcsSniff("Generic.VersionControl.SubversionProperties", null, null));
        this.add(new PhpcsSniff("Generic.WhiteSpace.DisallowTabIndent", null, null));
        this.add(new PhpcsSniff("Generic.WhiteSpace.ScopeIndent", null, null));
        this.add(new PhpcsSniff("MySource.CSS.BrowserSpecificStyles", null, null));
        this.add(new PhpcsSniff("MySource.Channels.ChannelException", null, null));
        this.add(new PhpcsSniff("MySource.Channels.DisallowSelfActions", null, null));
        this.add(new PhpcsSniff("MySource.Channels.IncludeSystem", null, null));
        this.add(new PhpcsSniff("MySource.Channels.UnusedSystem", null, null));
        this.add(new PhpcsSniff("MySource.Commenting.FunctionComment", "analyse function comments", "comment"));
        this.add(new PhpcsSniff("MySource.Debug.DebugCode", null, null));
        this.add(new PhpcsSniff("MySource.Debug.FirebugConsole", null, null));
        this.add(new PhpcsSniff("MySource.Objects.AssignThis", null, null));
        this.add(new PhpcsSniff("MySource.Objects.CreateWidgetTypeCallback", null, null));
        this.add(new PhpcsSniff("MySource.Objects.DisallowNewWidget", null, null));
        this.add(new PhpcsSniff("MySource.PHP.EvalObjectFactory", null, null));
        this.add(new PhpcsSniff("MySource.PHP.GetRequestData", null, null));
        this.add(new PhpcsSniff("MySource.PHP.ReturnFunctionValue", null, null));
        this.add(new PhpcsSniff("MySource.Strings.JoinStrings", null, null));
        this.add(new PhpcsSniff("PEAR.Classes.ClassDeclaration", null, null));
        this.add(new PhpcsSniff("PEAR.Commenting.ClassComment", "analyse class comments", "comment"));
        this.add(new PhpcsSniff("PEAR.Commenting.FileComment", "analyse file comments", "comment"));
        this.add(new PhpcsSniff("PEAR.Commenting.FunctionComment", "analyse function comments", "comment"));
        this.add(new PhpcsSniff("PEAR.Commenting.InlineComment", "analyse inline comments", "comment"));
        this.add(new PhpcsSniff("PEAR.ControlStructures.ControlSignature", null, null));
        this.add(new PhpcsSniff("PEAR.ControlStructures.MultiLineCondition", null, null));
        this.add(new PhpcsSniff("PEAR.Files.IncludingFile", null, null));
        this.add(new PhpcsSniff("PEAR.Formatting.MultiLineAssignment", null, null));
        this.add(new PhpcsSniff("PEAR.Functions.FunctionCallSignature", null, null));
        this.add(new PhpcsSniff("PEAR.Functions.FunctionDeclaration", null, null));
        this.add(new PhpcsSniff("PEAR.Functions.ValidDefaultValue", null, null));
        this.add(new PhpcsSniff("PEAR.NamingConventions.ValidClassName", null, null));
        this.add(new PhpcsSniff("PEAR.NamingConventions.ValidFunctionName", null, null));
        this.add(new PhpcsSniff("PEAR.NamingConventions.ValidVariableName", null, null));
        this.add(new PhpcsSniff("PEAR.WhiteSpace.ObjectOperatorIndent", null, null));
        this.add(new PhpcsSniff("PEAR.WhiteSpace.ScopeClosingBrace", null, null));
        this.add(new PhpcsSniff("PEAR.WhiteSpace.ScopeIndent", null, null));
        this.add(new PhpcsSniff("Squiz.Arrays.ArrayBracketSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.Arrays.ArrayDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.ClassDefinitionClosingBraceSpace", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.ClassDefinitionNameSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.ClassDefinitionOpeningBraceSpace", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.ColonSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.ColourDefinition", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.DisallowMultipleStyleDefinitions", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.DuplicateClassDefinition", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.DuplicateStyleDefinition", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.EmptyClassDefinition", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.EmptyStyleDefinition", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.Indentation", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.LowercaseStyleDefinition", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.MissingColon", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.Opacity", null, null));
        this.add(new PhpcsSniff("Squiz.CSS.SemicolonSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.Classes.ClassDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.Classes.ClassFileName", null, null));
        this.add(new PhpcsSniff("Squiz.Classes.DuplicateProperty", null, null));
        this.add(new PhpcsSniff("Squiz.Classes.LowercaseClassKeywords", null, null));
        this.add(new PhpcsSniff("Squiz.Classes.SelfMemberReference", null, null));
        this.add(new PhpcsSniff("Squiz.Classes.ValidClassName", null, null));
        this.add(new PhpcsSniff("Squiz.CodeAnalysis.EmptyStatement", null, null));
        this.add(new PhpcsSniff("Squiz.Commenting.BlockComment", "analyse block comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.ClassComment", "analyse class comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.ClosingDeclarationComment", "analyse closing declaration comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.DocCommentAlignment", "analyse alignment in comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.EmptyCatchComment", "analyse comments in empty catch clause", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.FileComment", "analyse file comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.FunctionComment", "analyse function comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.FunctionCommentThrowTag", "force @throws tags at Exception throwing Functions", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.InlineComment", "analyse inline comments", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.LongConditionClosingComment", "force comments at the end of long conditions", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.PostStatementComment", "analyse comments after statements", "comment"));
        this.add(new PhpcsSniff("Squiz.Commenting.VariableComment", "analyse variable comments", "comment"));
        this.add(new PhpcsSniff("Squiz.ControlStructures.ControlSignature", null, null));
        this.add(new PhpcsSniff("Squiz.ControlStructures.ElseIfDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.ControlStructures.ForEachLoopDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.ControlStructures.ForLoopDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.ControlStructures.InlineIfDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.ControlStructures.LowercaseDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.ControlStructures.SwitchDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.Debug.JSLint", null, null));
        this.add(new PhpcsSniff("Squiz.Debug.JavaScriptLint", null, null));
        this.add(new PhpcsSniff("Squiz.Files.FileExtension", null, null));
        this.add(new PhpcsSniff("Squiz.Formatting.OperatorBracket", null, null));
        this.add(new PhpcsSniff("Squiz.Functions.FunctionDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.Functions.FunctionDeclarationArgumentSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.Functions.FunctionDuplicateArgument", null, null));
        this.add(new PhpcsSniff("Squiz.Functions.GlobalFunction", null, null));
        this.add(new PhpcsSniff("Squiz.Functions.LowercaseFunctionKeywords", null, null));
        this.add(new PhpcsSniff("Squiz.Functions.MultiLineFunctionDeclaration", null, null));
        this.add(new PhpcsSniff("Squiz.NamingConventions.ConstantCase", null, null));
        this.add(new PhpcsSniff("Squiz.NamingConventions.ValidFunctionName", null, null));
        this.add(new PhpcsSniff("Squiz.NamingConventions.ValidVariableName", null, null));
        this.add(new PhpcsSniff("Squiz.Objects.DisallowObjectStringIndex", null, null));
        this.add(new PhpcsSniff("Squiz.Objects.ObjectInstantiation", null, null));
        this.add(new PhpcsSniff("Squiz.Objects.ObjectMemberComma", null, null));
        this.add(new PhpcsSniff("Squiz.Operators.ComparisonOperatorUsage", null, null));
        this.add(new PhpcsSniff("Squiz.Operators.IncrementDecrementUsage", null, null));
        this.add(new PhpcsSniff("Squiz.Operators.ValidLogicalOperators", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.CommentedOutCode", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.DisallowComparisonAssignment", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.DisallowInlineIf", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.DisallowMultipleAssignments", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.DisallowObEndFlush", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.DisallowSizeFunctionsInLoops", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.DiscouragedFunctions", "highlight discouraged functions", "forbidden"));
        this.add(new PhpcsSniff("Squiz.PHP.EmbeddedPhp", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.Eval", "highlight eval expressions", "forbidden"));
        this.add(new PhpcsSniff("Squiz.PHP.ForbiddenFunctions", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.GlobalKeyword", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.Heredoc", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.InnerFunctions", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.LowercasePHPFunctions", null, null));
        this.add(new PhpcsSniff("Squiz.PHP.NonExecutableCode", "show unreachable code", "unreachable"));
        this.add(new PhpcsSniff("Squiz.Scope.MemberVarScope", null, null));
        this.add(new PhpcsSniff("Squiz.Scope.MethodScope", null, null));
        this.add(new PhpcsSniff("Squiz.Scope.StaticThisUsage", null, null));
        this.add(new PhpcsSniff("Squiz.Strings.ConcatenationSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.Strings.DoubleQuoteUsage", null, null));
        this.add(new PhpcsSniff("Squiz.Strings.EchoedStrings", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.CastSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.ControlStructureSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.FunctionClosingBraceSpace", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.FunctionOpeningBraceSpace", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.FunctionSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.LanguageConstructSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.LogicalOperatorSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.MemberVarSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.ObjectOperatorSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.OperatorSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.PropertyLabelSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.ScopeClosingBrace", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.ScopeKeywordSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.SemicolonSpacing", null, null));
        this.add(new PhpcsSniff("Squiz.WhiteSpace.SuperfluousWhitespace", null, null));
        this.add(new PhpcsSniff("Zend.Debug.CodeAnalyzer", null, null));
        this.add(new PhpcsSniff("Zend.Files.ClosingTag", null, null));
        this.add(new PhpcsSniff("Zend.NamingConventions.ValidVariableName", null, null));
}}