/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.foopara.phpcsmd.ui;

import org.openide.util.Lookup;

import de.foopara.phpcsmd.generics.GenericOptionsPanel;

public class PropertyPanel extends GenericOptionsPanel
{

    protected Lookup lkp;

    public PropertyPanel() {
        this(null);
    }

    /**
     * Creates new form PropertyPanel
     */
    public PropertyPanel(Lookup lkp) {
        super();
        this.lkp = lkp;
        initComponents();
        this.load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        generalPropertyPanel1 = new de.foopara.phpcsmd.ui.GeneralPropertyPanel(this.lkp);
        phpcsPropertyPanel1 = new de.foopara.phpcsmd.ui.phpcs.PhpcsPropertyPanel(this.lkp);
        phpmdPropertyPanel1 = new de.foopara.phpcsmd.ui.phpmd.PhpmdPropertyPanel(this.lkp);
        phpcpdPropertyPanel1 = new de.foopara.phpcsmd.ui.phpcpd.PhpcpdPropertyPanel(this.lkp);
        pdependPropertyPanel1 = new de.foopara.phpcsmd.ui.pdepend.PdependPropertyPanel(this.lkp);

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        generalPropertyPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(generalPropertyPanel1);

        phpcsPropertyPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(phpcsPropertyPanel1);
        jPanel1.add(phpmdPropertyPanel1);
        jPanel1.add(phpcpdPropertyPanel1);
        jPanel1.add(pdependPropertyPanel1);

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.foopara.phpcsmd.ui.GeneralPropertyPanel generalPropertyPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private de.foopara.phpcsmd.ui.pdepend.PdependPropertyPanel pdependPropertyPanel1;
    private de.foopara.phpcsmd.ui.phpcpd.PhpcpdPropertyPanel phpcpdPropertyPanel1;
    private de.foopara.phpcsmd.ui.phpcs.PhpcsPropertyPanel phpcsPropertyPanel1;
    private de.foopara.phpcsmd.ui.phpmd.PhpmdPropertyPanel phpmdPropertyPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void load() {
        generalPropertyPanel1.load();
        phpcsPropertyPanel1.load();
        phpmdPropertyPanel1.load();
        phpcpdPropertyPanel1.load();
        pdependPropertyPanel1.load();
    }

    @Override
    public void save() {
        generalPropertyPanel1.save();
        phpcsPropertyPanel1.save();
        phpmdPropertyPanel1.save();
        phpcpdPropertyPanel1.save();
        pdependPropertyPanel1.save();
    }

    @Override
    public boolean hasValidValues() {
        return true;
    }

}
