/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.foopara.phpcsmd.ui;

import de.foopara.phpcsmd.generics.GenericOptionsPanel;

/**
 *
 * @author n.specht
 */
public class PropertyPanel extends GenericOptionsPanel {

    /**
     * Creates new form PropertyPanel
     */
    public PropertyPanel() {
        initComponents();
        this.load();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        phpcsPropertyPanel1 = new de.foopara.phpcsmd.ui.phpcs.PhpcsPropertyPanel();
        generalPropertyPanel1 = new de.foopara.phpcsmd.ui.GeneralPropertyPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        add(phpcsPropertyPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        add(generalPropertyPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.foopara.phpcsmd.ui.GeneralPropertyPanel generalPropertyPanel1;
    private de.foopara.phpcsmd.ui.phpcs.PhpcsPropertyPanel phpcsPropertyPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void load() {
        generalPropertyPanel1.load();
        phpcsPropertyPanel1.load();
    }

    @Override
    public void save() {
        generalPropertyPanel1.save();
        phpcsPropertyPanel1.save();
    }

    @Override
    public boolean hasValidValues() {
        return true;
    }
}
