package de.foopara.phpcsmd.ui.reports;

import de.foopara.phpcsmd.exec.pdepend.PdependTypes;
import javax.swing.JProgressBar;
import org.openide.util.Lookup;

/**
 *
 * @author nspecht
 */
public class PdependFunctionPanel extends PdependGenericResultPanel {

    /**
     * Creates new form PdependMethodPanel
     */
    public PdependFunctionPanel(Lookup lkp) {
        super(lkp);
        initComponents();
        this.addLabel("name", "Name", "Function");
        this.addSeparator(null, "Codelines", "Function");
        this.addLabel("loc", "Lines of Code", "Function");
        this.addProgressbar("ncloc", "Non Comment Lines of Code", "Function");
        this.addProgressbar("cloc", "Comment Lines of Code", "Function");
        this.addProgressbar("eloc", "Executable Lines of Code", "Function");
        this.addProgressbar("lloc", "Logical Lines Of Code", "Function");

        this.addSeparator(null, "Complexity", "Different Metrics");
        this.addLabel("ccn", "Cyclomatic Complexity", "Different Metrics");
        this.addLabel("ccn2", "Cyclomatic Complexity Number", "Different Metrics");
        this.addLabel("npath", "NPath Complexity", "Different Metrics");
    }

    public void setFunction(PdependTypes.PdependFunction func) {
        ((JProgressBar)this.elements.get("ncloc")).setMaximum(func.loc);
        ((JProgressBar)this.elements.get("cloc")).setMaximum(func.loc);
        ((JProgressBar)this.elements.get("eloc")).setMaximum(func.loc);
        ((JProgressBar)this.elements.get("lloc")).setMaximum(func.loc);
        this.setFields(func);
        this.setEditorButton(func.getFilename());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
