/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.foopara.phpcsmd.ui.reports;

import de.foopara.phpcsmd.exec.pdepend.PdependTypes;
import de.foopara.phpcsmd.option.PdependOptions;
import javax.swing.JProgressBar;

/**
 *
 * @author n.specht
 */
public class PdependMetricsPanel extends PdependGenericResultPanel {

    /**
     * Creates new form PdependMetricsPanel
     */
    public PdependMetricsPanel() {
        super();
        initComponents();
        this.addLabel("pdepend", "Pdepend Version", "Metrics");
        this.addLabel("generated", "Generated", "Metrics");

        this.addSeparator(null, "Codelines", "Metrics");
        this.addLabel("loc", "Lines of Code", "Metrics");
        this.addProgressbar("ncloc", "Non Comment Lines of Code", "Metrics");
        this.addProgressbar("cloc", "Comment Lines of Code", "Metrics");
        this.addProgressbar("eloc", "Executable Lines of Code", "Metrics");
        this.addProgressbar("lloc", "Logical Lines Of Code", "Metrics");

        if (!PdependOptions.getUseTabs()) {
            this.addSeparator(null, "Counts", "Counts");
        }
        this.addLabel("nop", "Number of Packages", "Counts");
        this.addLabel("noc", "Number of Classes", "Counts");
        this.addLabel("noi", "Number of Interfaces", "Counts");
        this.addLabel("nom", "Number of Methods", "Counts");
        this.addLabel("nof", "Number of Functions", "Counts");

        if (!PdependOptions.getUseTabs()) {
            this.addSeparator(null, "Classes", "Classes");
        }
        this.addProgressbar("roots", "Number of Root Classes", "Classes");
        this.addProgressbar("leafs", "Number of Leaf (final) Classes", "Classes");
        this.addProgressbar("clsc", "Number of Concrete Classes", "Classes");
        this.addProgressbar("clsa", "Number of Abstract Classes", "Classes");

        this.addLabel("ahh", "Average Hierarchy Height", "Classes");
        this.addLabel("andc", "Average Number of Derived Classes", "Classes");

        this.addSeparator(null, "Complexity", "Different Metrics");
        this.addLabel("ccn", "Cyclomatic Complexity", "Different Metrics");
        this.addLabel("ccn2", "Cyclomatic Complexity Number", "Different Metrics");

        this.addSeparator(null, null, "Different Metrics");
        this.addLabel("calls", "Number of Method or Function Calls", "Different Metrics");
        this.addLabel("fanout", "Number of Fanouts", "Different Metrics");



    }

    public void setMetrics(PdependTypes.PdependMetrics metrics) {
        ((JProgressBar)this.elements.get("ncloc")).setMaximum(metrics.loc);
        ((JProgressBar)this.elements.get("cloc")).setMaximum(metrics.loc);
        ((JProgressBar)this.elements.get("eloc")).setMaximum(metrics.loc);
        ((JProgressBar)this.elements.get("lloc")).setMaximum(metrics.loc);

        ((JProgressBar)this.elements.get("roots")).setMaximum(metrics.noc);
        ((JProgressBar)this.elements.get("leafs")).setMaximum(metrics.noc);
        ((JProgressBar)this.elements.get("clsc")).setMaximum(metrics.noc);
        ((JProgressBar)this.elements.get("clsa")).setMaximum(metrics.noc);

        this.setFields(metrics);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
