/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.foopara.phpcsmd.ui.reports;

import de.foopara.phpcsmd.exec.pdepend.PdependTypes;

/**
 *
 * @author nspecht
 */
public class PdependPackagePanel extends PdependGenericResultPanel {

    /**
     * Creates new form PdependPackagePanel
     */
    public PdependPackagePanel() {
        super();
        initComponents();
        this.addLabel("name", "Name", "Package");
        this.addSeparator(null, "Counts", "Package");
        this.addLabel("noc", "Number of Classes", "Package");
        this.addLabel("noi", "Number of Interfaces", "Package");
        this.addLabel("nom", "Number of Methods", "Package");
        this.addLabel("nof", "Number of Functions", "Package");

        this.addSeparator(null, "Code Rank", "Different Metrics");
        this.addLabel("cr", "Code Rank", "Different Metrics");
        this.addLabel("rcr", "Reverse Code Rank", "Different Metrics");
    }

    public void setPackage(PdependTypes.PdependPackage pack) {
        this.setFields(pack);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
