/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.foopara.phpcsmd.ui.reports;

import de.foopara.phpcsmd.exec.pdepend.PdependTypes;
import javax.swing.JProgressBar;

/**
 *
 * @author nspecht
 */
public class PdependMethodPanel extends PdependGenericResultPanel {

    /**
     * Creates new form PdependMethodPanel
     */
    public PdependMethodPanel() {
        initComponents();
        this.addLabel("name", "Name");
        this.addSeparator(null, "Complexity");
        this.addLabel("ccn", "Cyclomatic Complexity");
        this.addLabel("ccn2", "Cyclomatic Complexity Number");
        this.addLabel("npath", "NPath Complexity");

        this.addSeparator(null, "Codelines");
        this.addLabel("loc", "Lines of Code");
        this.addProgressbar("ncloc", "Non Comment Lines of Code");
        this.addProgressbar("cloc", "Comment Lines of Code");
        this.addProgressbar("eloc", "Executable Lines of Code");
        this.addProgressbar("lloc", "Logical Lines Of Code");
    }

    public void setMethod(PdependTypes.PdependMethod method) {
        ((JProgressBar)this.elements.get("ncloc")).setMaximum(method.loc);
        ((JProgressBar)this.elements.get("cloc")).setMaximum(method.loc);
        ((JProgressBar)this.elements.get("eloc")).setMaximum(method.loc);
        ((JProgressBar)this.elements.get("lloc")).setMaximum(method.loc);
        this.setFields(method);
        this.setEditorButton(method.getFilename());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
