/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.foopara.phpcsmd.ui.reports;

import de.foopara.phpcsmd.exec.pdepend.PdependTypes;

/**
 *
 * @author nspecht
 */
public class PdependPackagePanel extends PdependGenericResultPanel {

    /**
     * Creates new form PdependPackagePanel
     */
    public PdependPackagePanel() {
        initComponents();
        this.addLabel("name", "Name");
        this.addSeparator(null, "Counts");
        this.addLabel("noc", "Number of Classes");
        this.addLabel("noi", "Number of Interfaces");
        this.addLabel("nom", "Number of Methods");
        this.addLabel("nof", "Number of Functions");

        this.addSeparator(null, "Code Rank");
        this.addLabel("cr", "Code Rank");
        this.addLabel("rcr", "Reverse Code Rank");
    }

    public void setPackage(PdependTypes.PdependPackage pack) {
        this.setFields(pack);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
